kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: api-build
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'api-image:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'python:3.6'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/opendatahub-io/jupyterhub-singleuser-profiles.git'
      ref: master
  triggers:
    - type: ImageChange
    - type: ConfigChange
  runPolicy: Serial
